/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { XusdCredit, XusdCreditInterface } from "../XusdCredit";

const _abi = [
  {
    type: "event",
    name: "ClosePosition",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "timestamp",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreatePosition",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "liquidationPrice",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256",
        name: "collateralAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "body",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "borrowFee",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "timestamp",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Liquidation",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
        indexed: false,
      },
      {
        type: "uint256",
        name: "collateralAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "body",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        type: "address",
        name: "previousOwner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "newOwner",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdatePosition",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "newLiquidationPrice",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256",
        name: "newCollateralAmount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "newBody",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "newInterest",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "newBorrowFee",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "timestamp",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "contract IXUSD",
      },
    ],
    name: "XUSD",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "addCollateral",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint32",
        name: "",
        internalType: "uint32",
      },
    ],
    name: "borrowFeePercentagePoint",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "calculateInterest",
    inputs: [
      {
        type: "uint256",
        name: "_body",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "_lastUpdateTime",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "calculateLiquidationPrice",
    inputs: [
      {
        type: "uint256",
        name: "amountXUSD",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "collateralAmount",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "closePosition",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint8",
        name: "",
        internalType: "uint8",
      },
    ],
    name: "collateralPriceDecimals",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint8",
        name: "",
        internalType: "uint8",
      },
    ],
    name: "collateralRatio",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "createNewPosition",
    inputs: [
      {
        type: "address",
        name: "_sender",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "_collateralAmount",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "_body",
        internalType: "uint256",
      },
      {
        type: "uint64",
        name: "_liquidationPrice",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint8",
        name: "",
        internalType: "uint8",
      },
    ],
    name: "decimalsXUSD",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "getAccumulatedFees",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "getAccumulatedPenalties",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct Credit.Position",
        components: [
          {
            type: "bool",
            name: "isInitialized",
            internalType: "bool",
          },
          {
            type: "uint32",
            name: "creationTime",
            internalType: "uint32",
          },
          {
            type: "uint32",
            name: "lastUpdateTime",
            internalType: "uint32",
          },
          {
            type: "uint64",
            name: "liquidationPrice",
            internalType: "uint64",
          },
          {
            type: "uint112",
            name: "interest",
            internalType: "uint112",
          },
          {
            type: "uint112",
            name: "borrowFee",
            internalType: "uint112",
          },
          {
            type: "uint256",
            name: "collateralAmount",
            internalType: "uint256",
          },
          {
            type: "uint256",
            name: "body",
            internalType: "uint256",
          },
        ],
      },
    ],
    name: "getPosition",
    inputs: [
      {
        type: "address",
        name: "positionOwner",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "int256",
        name: "",
        internalType: "int256",
      },
    ],
    name: "getPriceFeeds",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "getTotalDebt",
    inputs: [
      {
        type: "address",
        name: "_position",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "init",
    inputs: [
      {
        type: "address",
        name: "_xusdAddress",
        internalType: "address",
      },
      {
        type: "address",
        name: "_priceOracle",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint32",
        name: "",
        internalType: "uint32",
      },
    ],
    name: "interestPercentagePoints",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "liquidate",
    inputs: [
      {
        type: "address",
        name: "positionOwner",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint32",
        name: "",
        internalType: "uint32",
      },
    ],
    name: "liquidationBonusPercentagePoint",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint32",
        name: "",
        internalType: "uint32",
      },
    ],
    name: "liquidationPenaltyPercentagePoint",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint8",
        name: "",
        internalType: "uint8",
      },
    ],
    name: "liquidationRatio",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "mintToUser",
    inputs: [
      {
        type: "address",
        name: "user",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "address",
      },
    ],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "pause",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "bool",
        name: "",
        internalType: "bool",
      },
    ],
    name: "paused",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint32",
        name: "",
        internalType: "uint32",
      },
    ],
    name: "precisionMultiplier",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "address",
        name: "",
        internalType: "contract AggregatorInterface",
      },
    ],
    name: "priceOracle",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceOwnership",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "repayLoan",
    inputs: [
      {
        type: "uint256",
        name: "amountXUSD",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setMaxAmountToMint",
    inputs: [
      {
        type: "uint256",
        name: "value",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setTestPrice",
    inputs: [
      {
        type: "int256",
        name: "newPrice",
        internalType: "int256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "takeAdditionalLoan",
    inputs: [
      {
        type: "uint256",
        name: "amountToMint",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "takeLoan",
    inputs: [
      {
        type: "uint256",
        name: "amountOut",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "int256",
        name: "",
        internalType: "int256",
      },
    ],
    name: "testPrice",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnership",
    inputs: [
      {
        type: "address",
        name: "newOwner",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnershipXUSD",
    inputs: [
      {
        type: "address",
        name: "newOwner",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "unpause",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "updatePosition",
    inputs: [
      {
        type: "address",
        name: "owner",
        internalType: "address",
      },
      {
        type: "uint256",
        name: "newCollateralAmount",
        internalType: "uint256",
      },
      {
        type: "uint256",
        name: "newBody",
        internalType: "uint256",
      },
      {
        type: "uint112",
        name: "newInterest",
        internalType: "uint112",
      },
      {
        type: "uint112",
        name: "newBorrowFee",
        internalType: "uint112",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawAccumelatedFees",
    inputs: [
      {
        type: "address",
        name: "receiver",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawAccumulatedPenalties",
    inputs: [
      {
        type: "address",
        name: "receiver",
        internalType: "address",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawCollateralFromPosition",
    inputs: [
      {
        type: "uint256",
        name: "withdrawAmount",
        internalType: "uint256",
      },
    ],
  },
];

export class XusdCredit__factory {
  static readonly abi = _abi;
  static createInterface(): XusdCreditInterface {
    return new utils.Interface(_abi) as XusdCreditInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): XusdCredit {
    return new Contract(address, _abi, signerOrProvider) as XusdCredit;
  }
}
